//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public long ItemID { get; set; }
        public Nullable<int> PastPaperId { get; set; }
        public long CartId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Qty { get; set; }
        public string ItemName { get; set; }
    
        public virtual PastPaper PastPaper { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
