//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMapDetail
    {
        public long HotSpotID { get; set; }
        public int ExamId { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string CreatedType { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
