//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamMapDetails = new HashSet<ExamMapDetail>();
            this.StudentsMcqAnswers = new HashSet<StudentsMcqAnswer>();
            this.TutorHotSpots = new HashSet<TutorHotSpot>();
            this.UploadImages = new HashSet<UploadImage>();
        }
    
        public int ExamID { get; set; }
        public int StudentLoginId { get; set; }
        public int ExamTypeId { get; set; }
        public int MediumId { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> PastPaperId { get; set; }
        public Nullable<int> Tutor1LoginId { get; set; }
        public Nullable<int> Tutor2LoginId { get; set; }
        public string AssignToTutor { get; set; }
        public Nullable<System.DateTime> AssignToTutorReadyDate { get; set; }
        public Nullable<System.DateTime> TutorApprovedDate { get; set; }
        public Nullable<System.DateTime> TutorDeadlineDate { get; set; }
        public Nullable<System.DateTime> TutorCompletedDate { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public string ExamNo { get; set; }
        public string FirstPaperAnswerSheetsPath { get; set; }
        public string SecondPaperAnswerSheetsPath { get; set; }
        public string FirstPaperMarkedSheetsPath { get; set; }
        public string SecondPaperMarkedSheetsPath { get; set; }
        public decimal FirstPaperMarks { get; set; }
        public decimal SecondPaperMarks { get; set; }
        public decimal TotalMarks { get; set; }
        public string StudentStatus { get; set; }
        public string TutorStatus { get; set; }
        public Nullable<bool> IsFirstPaperCompleted { get; set; }
        public bool IsSecondPaperCompleted { get; set; }
        public string TutorCommentsForFirstPaper { get; set; }
        public string TutorCommentsForSecondPaper { get; set; }
        public bool IsAdminAssignToTutor { get; set; }
        public string AdminAssignToTutorReason { get; set; }
        public decimal PriceForTutor { get; set; }
        public bool IsPaidForTutor { get; set; }
        public Nullable<System.DateTime> PaidDateForTutor { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsThirdPaperCompleted { get; set; }
        public int FirstPaperRemainingTime { get; set; }
        public int SecondPaperRemainingTime { get; set; }
        public int ThirdPaperRemainingTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMapDetail> ExamMapDetails { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Notification Notification { get; set; }
        public virtual PastPaper PastPaper { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsMcqAnswer> StudentsMcqAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorHotSpot> TutorHotSpots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadImage> UploadImages { get; set; }
    }
}
