//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedDetail
    {
        public long ID { get; set; }
        public long LoginId { get; set; }
        public System.DateTime LoggedDate { get; set; }
        public System.DateTime LoggedDateTime { get; set; }
    }
}
