//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class McqDetail
    {
        public long McqID { get; set; }
        public int Year { get; set; }
        public int SubjectID { get; set; }
        public int ExamTypeID { get; set; }
        public int QuestionNo { get; set; }
        public string Answer { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ExamType ExamType { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
