//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlinePaperMarkingEntities : DbContext
    {
        public OnlinePaperMarkingEntities()
            : base("name=OnlinePaperMarkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<ExamType> ExamTypes { get; set; }
        public virtual DbSet<McqDetail> McqDetails { get; set; }
        public virtual DbSet<Medium> Mediums { get; set; }
        public virtual DbSet<NotificationAssign> NotificationAssigns { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OnlineClass> OnlineClasses { get; set; }
        public virtual DbSet<OnlineUser> OnlineUsers { get; set; }
        public virtual DbSet<PastPaper> PastPapers { get; set; }
        public virtual DbSet<PreferedTutorExamType> PreferedTutorExamTypes { get; set; }
        public virtual DbSet<PreferedTutorMedium> PreferedTutorMediums { get; set; }
        public virtual DbSet<PreferedTutorSubject> PreferedTutorSubjects { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<StudentsMcqAnswer> StudentsMcqAnswers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ExamMapDetail> ExamMapDetails { get; set; }
        public virtual DbSet<UploadImage> UploadImages { get; set; }
        public virtual DbSet<TutorHotSpot> TutorHotSpots { get; set; }
        public virtual DbSet<SubjectImage> SubjectImages { get; set; }
        public virtual DbSet<tblTutor> tblTutors { get; set; }
        public virtual DbSet<OldUser> OldUsers { get; set; }
        public virtual DbSet<LoggedDetail> LoggedDetails { get; set; }
        public virtual DbSet<TutorQualification> TutorQualifications { get; set; }
        public virtual DbSet<PaperDownloadDetail> PaperDownloadDetails { get; set; }
        public virtual DbSet<PromoCode> PromoCodes { get; set; }
        public virtual DbSet<tblOnlineStudentMaster> tblOnlineStudentMasters { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
    }
}
