//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineUser
    {
        public long ID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> RecUser { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> TrnFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PassWordExpiryDate { get; set; }
        public string VerificationCode { get; set; }
        public string PasswordResetCode { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ProfileImagePath { get; set; }
        public int ProfileCompletionPercentage { get; set; }
    }
}
