//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDownloadDetail
    {
        public long DownloadID { get; set; }
        public int LoginId { get; set; }
        public int PaperId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
