//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PastPaper()
        {
            this.CartItems = new HashSet<CartItem>();
            this.Exams = new HashSet<Exam>();
        }
    
        public int PastPaerID { get; set; }
        public string PaperName { get; set; }
        public Nullable<int> Year { get; set; }
        public int SubjectID { get; set; }
        public int ExamTypeID { get; set; }
        public int MediumID { get; set; }
        public string BoxImagePath { get; set; }
        public string PaperPreviewPath { get; set; }
        public string PaperDownloadPath { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> McqQuestionCount { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool HasMcq { get; set; }
        public string MarkingSchemePath { get; set; }
        public bool HasMap { get; set; }
        public string MapImagePath { get; set; }
        public bool IsOnlineExam { get; set; }
        public Nullable<int> FirstPaperTime { get; set; }
        public Nullable<int> SecondPaperTime { get; set; }
        public bool IsActive { get; set; }
        public bool HasThirdPaper { get; set; }
        public Nullable<int> ThirdPaperTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
