//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferedTutorMedium
    {
        public int ID { get; set; }
        public int LoginId { get; set; }
        public int MediumId { get; set; }
        public string CreatedUser { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual Medium Medium { get; set; }
    }
}
