//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectImage
    {
        public int ImageID { get; set; }
        public int SubjectId { get; set; }
        public int MediumId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
