//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTutor
    {
        public int TutorID { get; set; }
        public string TutorInitials { get; set; }
        public string TutorFirstName { get; set; }
        public string TutorLastName { get; set; }
        public string TutorFullName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public string TutorEmail { get; set; }
        public Nullable<int> Religion { get; set; }
        public string Nationality { get; set; }
        public byte[] TutorImage { get; set; }
        public string FirstLanguage { get; set; }
        public string TutorNIC { get; set; }
        public string PostalID { get; set; }
        public string PassportID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public string PreviousTutorNo { get; set; }
        public string School_University { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string PreviousSchoolAddress { get; set; }
        public string AcademicYear { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AlternativeEmail { get; set; }
        public Nullable<int> LoginID { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<System.DateTime> RegistartionDate { get; set; }
        public string RegistrationFromTime { get; set; }
        public string RegistrationToTime { get; set; }
        public Nullable<bool> IsExported { get; set; }
        public string Medium { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string AccountNo { get; set; }
        public string Subject { get; set; }
        public string Occupation { get; set; }
        public int PendingExamsCount { get; set; }
        public string AdminApproval { get; set; }
        public int CompletedExamsCount { get; set; }
        public int DownloadedPaperCount { get; set; }
    
        public virtual District District1 { get; set; }
    }
}
