//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePapermarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadImage
    {
        public long ID { get; set; }
        public string ImageId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ExamId { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
